trigger:
  - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/Tabulate.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'
  buildVersion: '4.0.0'
  buildBranch: 'master'
  packageSuffix: 'beta'
  npm_config_cache: $(Pipeline.Workspace)/.npm  

steps:

- powershell: | # generates a hash of all packages.config and saves each on a single line on 'packages.hash.txt'
    Get-FileHash -Algorithm MD5 -Path (Get-ChildItem packages.config -Recurse) >> packages.hash.txt
    Write-Host "Hash File saved to packages.hash.txt"
  displayName: 'Calculate and save packages.config hash'

- task: Cache@2
  inputs:
    key: 'nuget | "$(Agent.OS)" | packages.hash.txt'
    restoreKeys: |
      nuget | "$(Agent.OS)"
      nuget
    path: packages 
  displayName: Cache NuGet packages

- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | ./tabulate/package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
    path: $(npm_config_cache)
  displayName: Cache npm

- script: npm ci
  workingDirectory: 'Tabulate'

- task: Bash@3
  displayName: 'Set environment variables'
  inputs:
    targetType: 'inline'
    script: |
      echo "##vso[task.setvariable variable=UMBRACO_PACKAGE_MIN_VERSION]$(System.UmbracoPackageMinVersion)"
      echo "##vso[task.setvariable variable=BUILD_VERSION]$(buildVersion).$(Build.BuildId)"
      echo "##vso[task.setvariable variable=REPO_TAG]'false'"      
      echo "##vso[task.setvariable variable=UMBRACO_PACKAGE_PRERELEASE_SUFFIX]$(packageSuffix)"
      echo "##vso[task.setvariable variable=BUILD_NUMBER]$(Build.BuildId)"  

- script: npm run build
  workingDirectory: 'Tabulate'

# install nuget tooling
- task: NuGetToolInstaller@1

# restore nuget packages for solution
- task: NuGetCommand@2
  displayName: 'Restore nuget packages for solution'
  inputs:
    restoreSolution: '$(solution)'

# build it
- task: MSBuild@1
  displayName: 'Build the sucker'
  inputs:
    solution: 'BuildPackage/package.proj'

- task: CopyFiles@2
  displayName: 'Copy package files from BuildPackage/artifacts to staging directory'
  inputs:     
    SourceFolder: 'BuildPackage/artifacts'
    Contents: '*.*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true

- task: PublishPipelineArtifact@0
  displayName: 'Publish zip and nuget from staging directory'
  inputs:
    artifactName: 'drop'
    targetPath: '$(Build.ArtifactStagingDirectory)'
